# Load Data

In [ ]:
import numpy as np
from scipy.optimize import curve_fit
from scipy.optimize import least_squares
import DC_Pickle as dcp
import Curve_Functions as cv
import matplotlib.pyplot as plt
%matplotlib inline

def disp_Data(x, y_true, y_pred, file_path, clt_num, cost, rows=1, columns=1):
    fig, ax = plt.subplots(rows, columns)
    ax.plot(x, y_true, '.', c='black', label='average score')
    ax.plot(x, y_pred, 'b-', label='curve fitting', linewidth=4)
    ax.set_xlim([0, max(x)+1])
    ax.set_ylim([0, max(y_true)+0.2])
    ax.legend(fontsize=14)
    ax.set_title("Cluster {0}: {1} errors loss".format(clt_num, round(cost, 2)))
    fig.savefig(file_path, dpi=100)
    plt.show()
    
train_idx = dcp.open_Pickle("../../data/pickles/clusters_origin/15attempts/indices/index13.pickle")
train_idx = train_idx[2] #2, 8

train_scores = dcp.open_Pickle('../../data/pickles/seperate_origin/eventValue.pickle')
train_scores = train_scores[:300, :]/1e+4
attempts50 = np.arange(50)+1
attempts300 = np.arange(300)+1

## filtering discontinuous under 15 attempts
idx_all = []
idx_pure = []

for i in range(train_scores.shape[1]):
    if not np.isnan(train_scores[:15, i]).any():
        idx_all.append(i)
        idx_pure.append(i)
    else:
        idx_all.append(np.nan)

train_scores = train_scores[:, idx_pure]
print("Training data set: {0}".format(np.shape(train_scores)))

## get cluster data and cluster average data (average is centroid)
nClt = 13
for i in range(nClt):
    name = "cluster{0}".format(i+1)
    globals()[name] = train_scores[:, train_idx==i] # get cluster data
    
    ## get cluster average data
    data = np.ones(300)
    for j in range(len(data)):
        avg = eval(name)[j, :]
        avg = np.sum(avg[~np.isnan(avg)])/len(avg[~np.isnan(avg)])
        data[j] = avg

    globals()["avg{0}".format(i+1)] = data
    
dcp.make_folders("../../Figs/curve_fitting/")

print("1:", np.shape(cluster1))
print("2:", np.shape(cluster2))
print("3:", np.shape(cluster3))
print("4:", np.shape(cluster4))
print("5:", np.shape(cluster5))
print("6:", np.shape(cluster6))
print("7:", np.shape(cluster7))
print("8:", np.shape(cluster8))
print("9:", np.shape(cluster9))
print("10:", np.shape(cluster10))
print("11:", np.shape(cluster11))
print("12:", np.shape(cluster12))
print("13:", np.shape(cluster13))

### power law fit

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

X = np.linspace(1, 10, 100)

poly1 = X + 1

exp1 = -2*np.exp(-X)+1
pow1 = -8*(X+2)**-2+1
step1 = np.ones(55)*2
Y = np.ones(100)
Y[45:] = step1
fig, ax = plt.subplots(2, 2, figsize = [10, 8])

ax[0, 0].plot(X, poly1, '-', c='navy', linewidth = 4)
#ax[0, 0].get_xaxis().set_visible(False)
#ax[0, 0].get_yaxis().set_visible(False)
ax[0, 0].set_ylim([0,max(poly1)])
ax[0, 0].set_title(r'1st Polynomial: $f(x)=x + 1$', fontsize=14)
ax[0, 0].tick_params(labelsize=12)
'''
ax[0, 1].plot(X, poly2, '-', c='navy', linewidth = 4)
ax[0, 1].get_xaxis().set_visible(False)
#ax[0, 1].get_yaxis().set_visible(False)
ax[0, 1].set_title(r'2nd Polynomial: $f(x)=x^2+1$')
'''
ax[0, 1].plot(X, exp1, '-', c='navy', linewidth = 4)
#ax[0, 1].get_xaxis().set_visible(False)
#ax[0, 1].get_yaxis().set_visible(False)
ax[0, 1].set_ylim([0,max(exp1)+0.2])
ax[0, 1].set_title(r'3 Params Exponetial: $f(x)=-2e^{-x}+1$', fontsize=14)
ax[0, 1].tick_params(labelsize=12)

ax[1, 0].plot(X, pow1, '-', c='navy', linewidth = 4)
#ax[1, 0].get_xaxis().set_visible(False)
#ax[1, 0].get_yaxis().set_visible(False)
ax[1, 0].set_ylim([0,max(pow1)+0.2])
ax[1, 0].set_title(r'4 Params Power: $f(x)=-8(x+2)^{-2}+1$', fontsize=14)
ax[1, 0].tick_params(labelsize=12)

ax[1, 1].plot(X, Y, '-', c='navy', linewidth = 4)
#ax[1, 0].get_xaxis().set_visible(False)
#ax[1, 0].get_yaxis().set_visible(False)
ax[1, 1].set_ylim([0,3])
ax[1, 1].set_title(r'step: transition point at 5', fontsize=14)
ax[1, 1].tick_params(labelsize=12)

fig.tight_layout()
#fig.savefig('/Users/PureMac/Documents/Project/Seongmuk/Analytics/Figs/Functions', dpi=100)

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

X = np.linspace(1, 50, 100)

exp1 = -2*np.exp(-X)+1
exp2 = -2*np.exp(-X)+1.5

pow1 = -8*(X+2)**-2+1
pow2 = -8*(X+2)**-2+1.5


step1 = np.ones(55)*1.5
Y = np.ones(100)
Y[45:] = step1
fig, ax = plt.subplots(1, 2, figsize = [10, 5])

ax[0].plot(X, exp1, '-', c='navy', linewidth = 4)
ax[0].plot(X+50, exp2, '-', c='maroon', linewidth = 4)
#ax[0, 0].get_xaxis().set_visible(False)
#ax[0, 0].get_yaxis().set_visible(False)
ax[0].set_ylim([0,max(exp2)+0.2])
ax[0].set_title('Piecewise Exponential', fontsize=14)
ax[0].tick_params(labelsize=12)


ax[1].plot(X, pow1, '-', c='navy', linewidth = 4)
ax[1].plot(X+50, pow2, '-', c='maroon', linewidth = 4)
#ax[0, 1].get_xaxis().set_visible(False)
#ax[0, 1].get_yaxis().set_visible(False)
ax[1].set_ylim([0,max(pow2)+0.2])
ax[1].set_title('Piecewise Power', fontsize=14)
ax[1].tick_params(labelsize=12)
'''
ax[1, 0].plot(X, pow1, '-', c='navy', linewidth = 4)
#ax[1, 0].get_xaxis().set_visible(False)
#ax[1, 0].get_yaxis().set_visible(False)
ax[1, 0].set_ylim([0,max(pow1)+0.2])
ax[1, 0].set_title(r'4 Params Power: $f(x)=-8(x+2)^{-2}+1$', fontsize=14)
ax[1, 0].tick_params(labelsize=12)

ax[1, 1].plot(X, Y, '-', c='navy', linewidth = 4)
#ax[1, 0].get_xaxis().set_visible(False)
#ax[1, 0].get_yaxis().set_visible(False)
ax[1, 1].set_ylim([0,3])
ax[1, 1].set_title(r'step: transition point at 5', fontsize=14)
ax[1, 1].tick_params(labelsize=12)
'''
fig.tight_layout()
fig.savefig('/Users/PureMac/Documents/Project/Seongmuk/Analytics/Figs/Piecewise_Functions', dpi=100)


# Multiple curve fitting

In [4]:
import numpy as np
from scipy.optimize import curve_fit
from scipy.optimize import least_squares
import DC_Pickle as dcp
import Curve_Functions as cv
import matplotlib.pyplot as plt
%matplotlib inline

def disp_Data(x, y_true, y_pred, file_path, clt_num, cost, rows=1, columns=1, size=(6, 4)):
    fig, ax = plt.subplots(rows, columns, figsize=size)
    ax.plot(x, y_true, 'rx', label='average score')
    ax.plot(x, y_pred, 'b-', label='curve fitting')
    ax.set_xlim([0, max(x)+1])
    ax.set_ylim([0, max(y_true)+0.2])
    ax.legend(fontsize=14)
    ax.set_title("cluster {0}: cost {1}".format(clt_num, round(cost, 2)))
    fig.savefig(file_path, dpi=100)
    plt.show()
    
train_idx = dcp.open_Pickle("../../data/pickles/clusters_origin/15attempts/indices/index13.pickle")
train_idx = train_idx[9] #2, 8

train_scores = dcp.open_Pickle('../../data/pickles/seperate_origin/eventValue.pickle')
train_scores = train_scores[:300, :]/1e+4
attempts15 = np.arange(15)+1
attempts300 = np.arange(300)+1

## filtering discontinuous under 15 attempts
idx_all = []
idx_pure = []

for i in range(train_scores.shape[1]):
    if not np.isnan(train_scores[:15, i]).any():
        idx_all.append(i)
        idx_pure.append(i)
    else:
        idx_all.append(np.nan)

train_scores = train_scores[:, idx_pure]
print("Training data set: {0}".format(np.shape(train_scores)))

## get cluster data and cluster average data (average is centroid)
nClt = 13
for i in range(nClt):
    name = "cluster{0}".format(i+1)
    globals()[name] = train_scores[:, train_idx==i] # get cluster data
    
    ## get cluster average data
    data = np.ones(300)
    for j in range(len(data)):
        avg = eval(name)[j, :]
        avg = np.sum(avg[~np.isnan(avg)])/len(avg[~np.isnan(avg)])
        data[j] = avg

    globals()["avg{0}".format(i+1)] = data
    
dcp.make_folders("../../Figs/curve_fitting/")

Training data set: (300, 22832)
../../Figs/curve_fitting/ already present - Skipping pickling.


In [5]:
cost, min_length, min_indice = cv.multCurve_Fitting(avg2, cv.powerlaw_least4, s=[1, 1, 1, 1], w=50, p=3)

In [6]:
print(min_length)
print(min_indice)

(200.0, 50.0, 50.0)
(1.0, 201.0, 251.0)


In [7]:
def curve_Matrix(y_data, least_func, seed=[1,1], window=10, piece=4):
    ## set initial x ranges
    x_range = np.linspace(1, 300, 300)
    y_range = y_data
    for i in range(piece):
        if i < piece-1:
            locals()["x{0}".format(i)] = x_range[i*window:window*(i+1)]
            locals()["y{0}".format(i)] = y_range[i*window:window*(i+1)]
        else:
            locals()["x{0}".format(i)] = x_range[i*window:]
            locals()["y{0}".format(i)] = y_range[i*window:]
        # print("x:[{0}, {1}]".format(eval("x{0}".format(i))[0], eval("x{0}".format(i))[-1]))
        # print("y:[{0}, {1}]".format(eval("y{0}".format(i))[0], eval("y{0}".format(i))[-1]))
    
    ## make matrix
    count = 0
    mat_iter = len(eval("x{0}".format(piece-1)))
    while(mat_iter>window):
        mat_iter = mat_iter-window
        #print(mat_iter)
        count = count+1
    
    err_matrix = np.zeros([piece, count+1])
    idx_matrix = np.zeros([piece, count+1])
    len_matrix = np.zeros([piece, count+1])
    print(np.shape(err_matrix))
    
    ## change window for pieces except first pieces
    for group in range(piece-1):
        #print("\n\n - pieace ", piece-group-1)
        #print(" - x{0}:\n".format(piece-group-1), "[{0}, {1}]".format(eval("x{0}".format(piece-group-1))[0], eval("x{0}".format(piece-group-1))[-1]))        
        partition = 0
        
        ## save matrix
        lsq = least_squares(least_func, seed, args=(eval("x{0}".format(piece-group-1)), eval("y{0}".format(piece-group-1)))) # function fitting
        err_matrix[piece-group-1, partition] = lsq.cost # save cost
        idx_matrix[piece-group-1, partition] = eval("x{0}".format(piece-group-1))[0]#len(eval("x{0}".format(piece-group-1))) # save x values
        len_matrix[piece-group-1, partition] = len(eval("x{0}".format(piece-group-1))) # save x length
        #print("cost!!:", lsq.cost)
        
        while( len(eval("x{0}".format(piece-group-1))-window) > window):
            locals()["x{0}".format(piece-group-1)] = eval("x{0}".format(piece-group-1))[window:] # 마지막 piece의 첫번째를 window만큼 더한다.
            locals()["y{0}".format(piece-group-1)] = eval("y{0}".format(piece-group-1))[window:] # 마지막 piece의 첫번째를 window만큼 더한다.
            #print("[{0}, {1}]".format(eval("x{0}".format(piece-group-1))[0], eval("x{0}".format(piece-group-1))[-1]))
            partition = partition+1
            
            ## save matrix
            lsq = least_squares(least_func, seed, args=(eval("x{0}".format(piece-group-1)), eval("y{0}".format(piece-group-1)))) # function fitting
            err_matrix[piece-group-1, partition] = lsq.cost # save cost
            idx_matrix[piece-group-1, partition] = eval("x{0}".format(piece-group-1))[0]# len(eval("x{0}".format(piece-group-1))) # save x values
            len_matrix[piece-group-1, partition] = len(eval("x{0}".format(piece-group-1))) # save x length
            #print("cost!!:", lsq.cost)
            
        end = eval("x{0}".format(piece-group-1))[0]
        #print("end: ", end)
        locals()["x{0}".format(piece-group-2)] = x_range[(piece-group-2)*window:int(end-1)] #처음의 값을 window만큼 이동
        locals()["y{0}".format(piece-group-2)] = y_range[(piece-group-2)*window:int(end-1)] #처음의 값을 window만큼 이동

    ## change window for first piece
    i = 0
    #print("\n\n - piece  0")
    #print(" - x0:\n", "[{0}, {1}]".format(eval("x0")[0], eval("x0")[-1]))
    ## save matrix
    lsq = least_squares(least_func, seed, args=(eval("x{0}".format(piece-group-1)), eval("y{0}".format(piece-group-1)))) # function fitting
    err_matrix[0, 0] = lsq.cost # save cost
    idx_matrix[0, 0] = eval("x0")[0]# len(eval("x0"))
    len_matrix[0, 0] = len(eval("x0"))
    while( len(eval("x0"))-window):
        end = eval("x0")[-1]
        locals()["x0"] = eval("x0")[:int(end-window)] # 마지막 piece의 첫번째를 window만큼 더한다.
        locals()["y0"] = eval("y0")[:int(end-window)] # 마지막 piece의 첫번째를 window만큼 더한다.
        #print("[{0}, {1}]".format(eval("x0")[0], eval("x0")[-1]))
        i = i+1
        
        ## save matrix
        lsq = least_squares(least_func, seed, args=(eval("x0"), eval("y0"))) # function fitting
        err_matrix[0, i] = lsq.cost # save cost
        idx_matrix[0, i] = eval("x0")[0]# len(eval("x0"))
        len_matrix[0, i] = len(eval("x0"))
        #print("cost!!:", lsq.cost)
                                               
    # print(err_matrix)
    return idx_matrix, err_matrix, len_matrix

In [11]:
init_param = [1, 1, 1, 1]
idx_matrix, err_matrix, len_matrix = curve_Matrix(avg2, cv.powerlaw_least4, seed=init_param, window=50, piece=4)

print(idx_matrix)
print(len_matrix)
print(err_matrix)
# print(err_matrix)

(4, 3)
[[   1.    1.    1.]
 [  51.  101.  151.]
 [ 101.  151.  201.]
 [ 151.  201.  251.]]
[[ 150.  100.   50.]
 [ 150.  100.   50.]
 [ 150.  100.   50.]
 [ 150.  100.   50.]]
[[  7.92523178   4.44579093   2.6933187 ]
 [ 13.62284232  11.96515371   7.92523178]
 [ 22.8948206   18.65926016  10.62574185]
 [ 49.33619102  41.31877251  30.63488561]]


$$
[[  9.12452726   2.44390664   1.41336831]
 [ 15.51915014  14.6532302    9.12452726]
 [ 26.46881336  21.0657057   11.73514471]
 [ 61.27820343  48.22486986  33.18208082]]
$$

In [ ]:
def curve2_Fitting(idxM, lenM, errM):
    groups, mat_iter = np.shape(lenM)
    pre_cost = np.nan # an argument to check successive cost
    min_cost = float('nan') # minimum cost
    min_l = [np.nan]*groups # minimum length
    bp = [np.nan]*groups # break points

    count = 0

    ## 1st piece
    for i1 in range(mat_iter):
        print('iter ', i1)
        p1 = idxM[0, i1]
        l1 = lenM[0, i1]
        c1 = errM[0, i1]
        
        ## 2nd piece
        for i2 in range(mat_iter):
            p2 = idxM[1, i2]
            l2 = lenM[1, i2]
            c2 = errM[1, i2]

            ## check whether range is 300 and index is valid
            true_range = l1+l2
            bp = p1, p2
            bp_checker = np.sort(bp) == bp
            if (true_range==300) and not(bp_checker.all() == False):
                sum_cost = c1+c2

                ## check a minimum cost
                if  count==0 or pre_cost > sum_cost:
                    #print("indd!!!!")
                    min_cost = sum_cost
                    min_l = l1, l2
                    count = count+1

                pre_cost = sum_cost

    print("min_cost: ", min_cost, "at {0} with {1}".format(bp, min_l))
    return min_cost, min_l, bp

In [ ]:
def curve3_Fitting(idxM, lenM, errM):
    groups, mat_iter = np.shape(lenM)
    pre_cost = np.nan # an argument to check successive cost
    min_cost = float('nan') # minimum cost
    min_l = [np.nan]*groups # minimum length
    bp = [np.nan]*groups # break points

    count = 0

    ## 1st piece
    for i1 in range(mat_iter):
        print('iter ', i1)
        p1 = idxM[0, i1]
        l1 = lenM[0, i1]
        c1 = errM[0, i1]
        
        ## 2nd piece
        for i2 in range(mat_iter):
            p2 = idxM[1, i2]
            l2 = lenM[1, i2]
            c2 = errM[1, i2]

            ## 3rd piece
            for i3 in range(mat_iter):
                p3 = idxM[2, i3]
                l3 = lenM[2, i3]
                c3 = errM[2, i3]

                ## check whether range is 300 and index is valid
                true_range = l1+l2+l3
                bp = p1, p2, p3
                bp_checker = np.sort(bp) == bp
                if (true_range==300) and not(bp_checker.all() == False):
                    sum_cost = c1+c2+c3

                    ## check a minimum cost
                    if  count==0 or pre_cost > sum_cost:
                        #print("indd!!!!")
                        min_cost = sum_cost
                        min_l = l1, l2, l3
                        count = count+1

                    pre_cost = sum_cost

    print("min_cost: ", min_cost, "at {0} with {1}".format(bp, min_l))
    return min_cost, min_l, bp

cost, min_length, min_indice = curve3_Fitting(idx_matrix, len_matrix, err_matrix)

In [ ]:
def curve4_Fitting(idxM, lenM, errM):
    groups, mat_iter = np.shape(lenM)
    pre_cost = np.nan # an argument to check successive cost
    min_cost = float('nan') # minimum cost
    min_l = [np.nan]*groups # minimum length
    bp = [np.nan]*groups # break points

    count = 0

    ## 1st piece
    for i1 in range(mat_iter):
        print('iter ', i1)
        p1 = idxM[0, i1]
        l1 = lenM[0, i1]
        c1 = errM[0, i1]
        
        ## 2nd piece
        for i2 in range(mat_iter):
            p2 = idxM[1, i2]
            l2 = lenM[1, i2]
            c2 = errM[1, i2]

            ## 3rd piece
            for i3 in range(mat_iter):
                p3 = idxM[2, i3]
                l3 = lenM[2, i3]
                c3 = errM[2, i3]
                
                ## 4th piece
                for i4 in range(mat_iter):
                    p4 = idxM[3, i4]
                    l4 = lenM[3, i4]
                    c4 = errM[3, i4]

                    ## check whether range is 300 and index is valid
                    true_range = l1+l2+l3+l4
                    bp = p1, p2, p3, p4
                    bp_checker = np.sort(bp) == bp
                    if (true_range==300) and not(bp_checker.all() == False):
                        sum_cost = c1+c2+c3+c4

                        ## check a minimum cost
                        if  count==0 or pre_cost > sum_cost:
                            #print("indd!!!!")
                            min_cost = sum_cost
                            min_l = l1, l2, l3, l4
                            count = count+1

                        pre_cost = sum_cost

    print("min_cost: ", min_cost, "at {0} with {1}".format(bp, min_l))
    return min_cost, min_l, bp

cost, min_length, min_indice = curve4_Fitting(idx_matrix, len_matrix, err_matrix)

In [ ]:
def curve5_Fitting(idxM, lenM, errM):
    groups, mat_iter = np.shape(lenM)
    pre_cost = np.nan # an argument to check successive cost
    min_cost = float('nan') # minimum cost
    min_l = [np.nan]*groups # minimum length
    bp = [np.nan]*groups # break points

    count = 0

    ## 1st piece
    for i1 in range(mat_iter):
        print('iter ', i1)
        p1 = idxM[0, i1]
        l1 = lenM[0, i1]
        c1 = errM[0, i1]
        
        ## 2nd piece
        for i2 in range(mat_iter):
            p2 = idxM[1, i2]
            l2 = lenM[1, i2]
            c2 = errM[1, i2]

            ## 3rd piece
            for i3 in range(mat_iter):
                p3 = idxM[2, i3]
                l3 = lenM[2, i3]
                c3 = errM[2, i3]
                
                ## 4th piece
                for i4 in range(mat_iter):
                    p4 = idxM[3, i4]
                    l4 = lenM[3, i4]
                    c4 = errM[3, i4]
                    
                    ## 4th piece
                    for i5 in range(mat_iter):
                        p5 = idxM[4, i5]
                        l5 = lenM[4, i5]
                        c5 = errM[4, i5]

                        ## check whether range is 300 and index is valid
                        true_range = l1+l2+l3+l4+l5
                        bp = p1, p2, p3, p4, p5
                        bp_checker = np.sort(bp) == bp
                        if (true_range==300) and not(bp_checker.all() == False):
                            sum_cost = c1+c2+c3+c4+c5

                            ## check a minimum cost
                            if  count==0 or pre_cost > sum_cost:
                                #print("indd!!!!")
                                min_cost = sum_cost
                                min_l = l1, l2, l3, l4, l5
                                count = count+1

                            pre_cost = sum_cost

    print("min_cost: ", min_cost, "at {0} with {1}".format(bp, min_l))
    return min_cost, min_l, bp

cost, min_length, min_indice = curve5_Fitting(idx_matrix, len_matrix, err_matrix)

In [ ]:
def curve6_Fitting(idxM, lenM, errM):
    groups, mat_iter = np.shape(lenM)
    pre_cost = np.nan # an argument to check successive cost
    min_cost = float('nan') # minimum cost
    min_l = [np.nan]*groups # minimum length
    bp = [np.nan]*groups # break points

    count = 0

    ## 1st piece
    for i1 in range(mat_iter):
        print('iter ', i1)
        p1 = idxM[0, i1]
        l1 = lenM[0, i1]
        c1 = errM[0, i1]
        
        ## 2nd piece
        for i2 in range(mat_iter):
            p2 = idxM[1, i2]
            l2 = lenM[1, i2]
            c2 = errM[1, i2]

            ## 3rd piece
            for i3 in range(mat_iter):
                p3 = idxM[2, i3]
                l3 = lenM[2, i3]
                c3 = errM[2, i3]
                
                ## 4th piece
                for i4 in range(mat_iter):
                    p4 = idxM[3, i4]
                    l4 = lenM[3, i4]
                    c4 = errM[3, i4]
                    
                    ## 5th piece
                    for i5 in range(mat_iter):
                        p5 = idxM[4, i5]
                        l5 = lenM[4, i5]
                        c5 = errM[4, i5]
                        
                        ## 6th piece
                        for i6 in range(mat_iter):
                            p6 = idxM[5, i6]
                            l6 = lenM[5, i6]
                            c6 = errM[5, i6]

                            ## check whether range is 300 and index is valid
                            true_range = l1+l2+l3+l4+l5+l6
                            bp = p1, p2, p3, p4, p5, p6
                            bp_checker = np.sort(bp) == bp
                            if (true_range==300) and not(bp_checker.all() == False):
                                sum_cost = c1+c2+c3+c4+c5+c6

                                ## check a minimum cost
                                if  count==0 or pre_cost > sum_cost:
                                    #print("indd!!!!")
                                    min_cost = sum_cost
                                    min_l = l1, l2, l3, l4, l5, l6
                                    count = count+1

                                pre_cost = sum_cost

    print("min_cost: ", min_cost, "at {0} with {1}".format(bp, min_l))
    return min_cost, min_l, bp

cost, min_length, min_indice = curve6_Fitting(idx_matrix, len_matrix, err_matrix)

In [ ]:
def curve7_Fitting(idxM, lenM, errM):
    groups, mat_iter = np.shape(lenM)
    pre_cost = np.nan # an argument to check successive cost
    min_cost = float('nan') # minimum cost
    min_l = [np.nan]*groups # minimum length
    bp = [np.nan]*groups # break points

    count = 0

    ## 1st piece
    for i1 in range(mat_iter):
        print('iter ', i1)
        p1 = idxM[0, i1]
        l1 = lenM[0, i1]
        c1 = errM[0, i1]
        
        ## 2nd piece
        for i2 in range(mat_iter):
            p2 = idxM[1, i2]
            l2 = lenM[1, i2]
            c2 = errM[1, i2]

            ## 3rd piece
            for i3 in range(mat_iter):
                p3 = idxM[2, i3]
                l3 = lenM[2, i3]
                c3 = errM[2, i3]
                
                ## 4th piece
                for i4 in range(mat_iter):
                    p4 = idxM[3, i4]
                    l4 = lenM[3, i4]
                    c4 = errM[3, i4]
                    
                    ## 5th piece
                    for i5 in range(mat_iter):
                        p5 = idxM[4, i5]
                        l5 = lenM[4, i5]
                        c5 = errM[4, i5]
                        
                        ## 6th piece
                        for i6 in range(mat_iter):
                            p6 = idxM[5, i6]
                            l6 = lenM[5, i6]
                            c6 = errM[5, i6]
                            
                            ## 7th piece
                            for i7 in range(mat_iter):
                                p7 = idxM[6, i7]
                                l7 = lenM[6, i7]
                                c7 = errM[6, i7]

                                ## check whether range is 300 and index is valid
                                true_range = l1+l2+l3+l4+l5+l6+l7
                                bp = p1, p2, p3, p4, p5, p6, p7
                                bp_checker = np.sort(bp) == bp
                                if (true_range==300) and not(bp_checker.all() == False):
                                    sum_cost = c1+c2+c3+c4+c5+c6+c7

                                    ## check a minimum cost
                                    if  count==0 or pre_cost > sum_cost:
                                        #print("indd!!!!")
                                        min_cost = sum_cost
                                        min_l = l1, l2, l3, l4, l5, l6, l7
                                        count = count+1

                                    pre_cost = sum_cost

    print("min_cost: ", min_cost, "at {0} with {1}".format(bp, min_l))
    return min_cost, min_l, bp

cost, min_length, min_indice = curve7_Fitting(idx_matrix, len_matrix, err_matrix)

In [ ]:
def curve8_Fitting(idxM, lenM, errM):
    groups, mat_iter = np.shape(lenM)
    pre_cost = np.nan # an argument to check successive cost
    min_cost = float('nan') # minimum cost
    min_l = [np.nan]*groups # minimum length
    bp = [np.nan]*groups # break points

    count = 0

    ## 1st piece
    for i1 in range(mat_iter):
        print('iter ', i1)
        p1 = idxM[0, i1]
        l1 = lenM[0, i1]
        c1 = errM[0, i1]
        
        ## 2nd piece
        for i2 in range(mat_iter):
            p2 = idxM[1, i2]
            l2 = lenM[1, i2]
            c2 = errM[1, i2]

            ## 3rd piece
            for i3 in range(mat_iter):
                p3 = idxM[2, i3]
                l3 = lenM[2, i3]
                c3 = errM[2, i3]
                
                ## 4th piece
                for i4 in range(mat_iter):
                    p4 = idxM[3, i4]
                    l4 = lenM[3, i4]
                    c4 = errM[3, i4]
                    
                    ## 5th piece
                    for i5 in range(mat_iter):
                        p5 = idxM[4, i5]
                        l5 = lenM[4, i5]
                        c5 = errM[4, i5]
                        
                        ## 6th piece
                        for i6 in range(mat_iter):
                            p6 = idxM[5, i6]
                            l6 = lenM[5, i6]
                            c6 = errM[5, i6]
                            
                            ## 7th piece
                            for i7 in range(mat_iter):
                                p7 = idxM[6, i7]
                                l7 = lenM[6, i7]
                                c7 = errM[6, i7]
                                
                                ## 8th piece
                                for i8 in range(mat_iter):
                                    p8 = idxM[7, i8]
                                    l8 = lenM[7, i8]
                                    c8 = errM[7, i8]

                                    ## check whether range is 300 and index is valid
                                    true_range = l1+l2+l3+l4+l5+l6+l7+l8
                                    bp = p1, p2, p3, p4, p5, p6, p7, p8
                                    bp_checker = np.sort(bp) == bp
                                    if (true_range==300) and not(bp_checker.all() == False):
                                        sum_cost = c1+c2+c3+c4+c5+c6+c7+c7

                                        ## check a minimum cost
                                        if  count==0 or pre_cost > sum_cost:
                                            #print("indd!!!!")
                                            min_cost = sum_cost
                                            min_l = l1, l2, l3, l4, l5, l6, l7, l8
                                            count = count+1

                                        pre_cost = sum_cost

    print("min_cost: ", min_cost, "at {0} with {1}".format(bp, min_l))
    return min_cost, min_l, bp

cost, min_length, min_indice = curve8_Fitting(idx_matrix, len_matrix, err_matrix)

In [ ]:
def curve9_Fitting(idxM, lenM, errM):
    groups, mat_iter = np.shape(lenM)
    pre_cost = np.nan # an argument to check successive cost
    min_cost = float('nan') # minimum cost
    min_l = [np.nan]*groups # minimum length
    bp = [np.nan]*groups # break points

    count = 0

    ## 1st piece
    for i1 in range(mat_iter):
        print('iter ', i1)
        p1 = idxM[0, i1]
        l1 = lenM[0, i1]
        c1 = errM[0, i1]
        
        ## 2nd piece
        for i2 in range(mat_iter):
            p2 = idxM[1, i2]
            l2 = lenM[1, i2]
            c2 = errM[1, i2]

            ## 3rd piece
            for i3 in range(mat_iter):
                p3 = idxM[2, i3]
                l3 = lenM[2, i3]
                c3 = errM[2, i3]
                
                ## 4th piece
                for i4 in range(mat_iter):
                    p4 = idxM[3, i4]
                    l4 = lenM[3, i4]
                    c4 = errM[3, i4]
                    
                    ## 5th piece
                    for i5 in range(mat_iter):
                        p5 = idxM[4, i5]
                        l5 = lenM[4, i5]
                        c5 = errM[4, i5]
                        
                        ## 6th piece
                        for i6 in range(mat_iter):
                            p6 = idxM[5, i6]
                            l6 = lenM[5, i6]
                            c6 = errM[5, i6]
                            
                            ## 7th piece
                            for i7 in range(mat_iter):
                                p7 = idxM[6, i7]
                                l7 = lenM[6, i7]
                                c7 = errM[6, i7]
                                
                                ## 8th piece
                                for i8 in range(mat_iter):
                                    p8 = idxM[7, i8]
                                    l8 = lenM[7, i8]
                                    c8 = errM[7, i8]
                                    
                                    ## 9th piece
                                    for i9 in range(mat_iter):
                                        p9 = idxM[8, i9]
                                        l9 = lenM[8, i9]
                                        c9 = errM[8, i9]

                                        ## check whether range is 300 and index is valid
                                        true_range = l1+l2+l3+l4+l5+l6+l7+l8+l9
                                        bp = p1, p2, p3, p4, p5, p6, p7, p8, p9
                                        bp_checker = np.sort(bp) == bp
                                        if (true_range==300) and not(bp_checker.all() == False):
                                            sum_cost = c1+c2+c3+c4+c5+c6+c7+c7+c9

                                            ## check a minimum cost
                                            if  count==0 or pre_cost > sum_cost:
                                                #print("indd!!!!")
                                                min_cost = sum_cost
                                                min_l = l1, l2, l3, l4, l5, l6, l7, l8, l9
                                                count = count+1

                                            pre_cost = sum_cost

    print("min_cost: ", min_cost, "at {0} with {1}".format(bp, min_l))
    return min_cost, min_l, bp

cost, min_length, min_indice = curve9_Fitting(idx_matrix, len_matrix, err_matrix)

In [ ]:
def curve10_Fitting(idxM, lenM, errM):
    groups, mat_iter = np.shape(lenM)
    pre_cost = np.nan # an argument to check successive cost
    min_cost = float('nan') # minimum cost
    min_l = [np.nan]*groups # minimum length
    bp = [np.nan]*groups # break points

    count = 0

    ## 1st piece
    for i1 in range(mat_iter):
        print('iter ', i1)
        p1 = idxM[0, i1]
        l1 = lenM[0, i1]
        c1 = errM[0, i1]
        
        ## 2nd piece
        for i2 in range(mat_iter):
            p2 = idxM[1, i2]
            l2 = lenM[1, i2]
            c2 = errM[1, i2]

            ## 3rd piece
            for i3 in range(mat_iter):
                p3 = idxM[2, i3]
                l3 = lenM[2, i3]
                c3 = errM[2, i3]
                
                ## 4th piece
                for i4 in range(mat_iter):
                    p4 = idxM[3, i4]
                    l4 = lenM[3, i4]
                    c4 = errM[3, i4]
                    
                    ## 5th piece
                    for i5 in range(mat_iter):
                        p5 = idxM[4, i5]
                        l5 = lenM[4, i5]
                        c5 = errM[4, i5]
                        
                        ## 6th piece
                        for i6 in range(mat_iter):
                            p6 = idxM[5, i6]
                            l6 = lenM[5, i6]
                            c6 = errM[5, i6]
                            
                            ## 7th piece
                            for i7 in range(mat_iter):
                                p7 = idxM[6, i7]
                                l7 = lenM[6, i7]
                                c7 = errM[6, i7]
                                
                                ## 8th piece
                                for i8 in range(mat_iter):
                                    p8 = idxM[7, i8]
                                    l8 = lenM[7, i8]
                                    c8 = errM[7, i8]
                                    
                                    ## 9th piece
                                    for i9 in range(mat_iter):
                                        p9 = idxM[8, i9]
                                        l9 = lenM[8, i9]
                                        c9 = errM[8, i9]
                                        
                                        ## 9th piece
                                        for i10 in range(mat_iter):
                                            p10 = idxM[9, i10]
                                            l10 = lenM[9, i10]
                                            c10 = errM[9, i10]

                                            ## check whether range is 300 and index is valid
                                            true_range = l1+l2+l3+l4+l5+l6+l7+l8+l9+l10
                                            bp = p1, p2, p3, p4, p5, p6, p7, p8, p9, p10
                                            bp_checker = np.sort(bp) == bp
                                            if (true_range==300) and not(bp_checker.all() == False):
                                                sum_cost = c1+c2+c3+c4+c5+c6+c7+c7+c9+c10

                                                ## check a minimum cost
                                                if  count==0 or pre_cost > sum_cost:
                                                    #print("indd!!!!")
                                                    min_cost = sum_cost
                                                    min_l = l1, l2, l3, l4, l5, l6, l7, l8, l9, l10
                                                    count = count+1

                                                pre_cost = sum_cost

    print("min_cost: ", min_cost, "at {0} with {1}".format(bp, min_l))
    return min_cost, min_l, bp

cost, min_length, min_indice = curve10_Fitting(idx_matrix, len_matrix, err_matrix)

In [ ]:
x_range = np.linspace(1, 300, 300)

fig, ax = plt.subplots(1, 1, figsize=(6.5, 5))
ax.plot(x_range, avg12, 'o', color='black')
ax.tick_params(labelsize=17)
y_range = np.linspace(0, 5, 100)
ax.plot(np.ones(100)*150, y_range, 'r-.', linewidth=3)
ax.plot(np.ones(100)*200, y_range, 'g-.', linewidth=3)
ax.plot(np.ones(100)*250, y_range, 'b-.', linewidth=3)
ax.set_xlim([0, max(x_range)])
ax.set_ylim([0, max(avg1)+0.2])
ax.get_yaxis().set_visible(False)
#ax.ylabel('Score', fontsize=14)
#ax.xlabel('Attempt', fontsize=14)
fig.savefig("/Users/PureMac/Desktop/7", dpi=100)
#plt.show()